### ISSUE TITLE
terminate called after throwing an instance of 'std::runtime_error'

### ISSUE THREAD

**Issue by whitesockcat** [Jittor/InstanceSegmentation-jittor#1]
When i run:
`cd /detectron.jittor/demo/`
`python test_maskrcnn.py`

get this output:

> [i 0130 18:07:07.834767 36 compiler.py:847] Jittor(1.2.2.22) src: /root/miniconda3/envs/myconda/lib/python3.7/site-packages/jittor
[i 0130 18:07:07.834909 36 compiler.py:848] g++ at /usr/bin/g++
[i 0130 18:07:07.835010 36 compiler.py:849] cache_path: /root/.cache/jittor/default/g++
[i 0130 18:07:07.845266 36 __init__.py:257] Found /usr/local/cuda/bin/nvcc(10.0.130) at /usr/local/cuda/bin/nvcc.
[i 0130 18:07:07.861888 36 __init__.py:257] Found addr2line(2.30) at /usr/bin/addr2line.
[i 0130 18:07:07.900882 36 compiler.py:889] pybind_include: -I/root/miniconda3/envs/myconda/include/python3.7m -I/root/miniconda3/envs/myconda/lib/python3.7/site-packages/pybind11/include
[i 0130 18:07:07.926310 36 compiler.py:891] extension_suffix: .cpython-37m-x86_64-linux-gnu.so
[i 0130 18:07:08.160195 36 __init__.py:169] Total mem: 62.54GB, using 16 procs for compiling.
[i 0130 18:07:08.292372 36 jit_compiler.cc:21] Load cc_path: /usr/bin/g++
[i 0130 18:07:08.453513 36 init.cc:54] Found cuda archs: [75,]
[i 0130 18:07:08.486432 36 compile_extern.py:384] mpicc not found, distribution disabled.
[i 0130 18:07:08.549991 36 compile_extern.py:16] found /usr/local/cuda/include/cublas.h
[i 0130 18:07:08.550087 36 compile_extern.py:16] found /usr/local/cuda/lib64/libcublas.so
[i 0130 18:07:08.821434 36 compile_extern.py:16] found /usr/include/cudnn.h
[i 0130 18:07:08.821595 36 compile_extern.py:16] found /usr/lib/x86_64-linux-gnu/libcudnn.so
[i 0130 18:07:08.851032 36 compiler.py:654] handle pyjt_include/root/miniconda3/envs/myconda/lib/python3.7/site-packages/jittor/extern/cuda/cudnn/inc/cudnn_warper.h
[i 0130 18:07:10.230110 36 compile_extern.py:16] found /usr/local/cuda/include/curand.h
[i 0130 18:07:10.230265 36 compile_extern.py:16] found /usr/local/cuda/lib64/libcurand.so
[i 0130 18:07:11.166735 36 cuda_flags.cc:26] CUDA enabled.
terminate called after throwing an instance of 'std::runtime_error'
  what():  [f 0130 18:07:18.423952 36 jit_key.cc:41] Check failed: 0== mprotect((void*)buffer_end_page, page_size, 0x1|0x2|0x4)  Something wrong... Could you please report this issue?

**Comment by Jittor** [comment]
thanks for your feedbacks, this it because jittor is incompatible with some version of pytorch, could you please try&nbsp;
&nbsp; &nbsp; python3.7 -m pip install torch==1.3.1 torchvision=0.4.2



---Original---

**Comment by Jittor** [comment]
Thanks for your feedbacks.
This is weird, can you try this test?python3.7 -m jittor.test.test_example
and this test?
python3.7 -m jittor.test.test_resnet

---Original---

**Comment by whitesockcat** [comment]
Solved! 
The error has nothing to do with codes, it's because of my platform setting.
THX!

> Thanks for your feedbacks. This is weird, can you try this test?python3.7 -m jittor.test.test_example and this test? python3.7 -m jittor.test.test_resnet
> […](#)
> ---Original--- From: "whitesockcat"<notifications@github.com&gt; Date: Sat, Jan 30, 2021 18:10 PM To: "Jittor/InstanceSegmentation-jittor"<InstanceSegmentation-jittor@noreply.github.com&gt;; Cc: "Subscribed"<subscribed@noreply.github.com&gt;; Subject: [Jittor/InstanceSegmentation-jittor] terminate called after throwing an instance of 'std::runtime_error' (#1) When i run: cd /detectron.jittor/demo/ python test_maskrcnn.py get this output: [i 0130 18:07:07.834767 36 compiler.py:847] Jittor(1.2.2.22) src: /root/miniconda3/envs/myconda/lib/python3.7/site-packages/jittor [i 0130 18:07:07.834909 36 compiler.py:848] g++ at /usr/bin/g++ [i 0130 18:07:07.835010 36 compiler.py:849] cache_path: /root/.cache/jittor/default/g++ [i 0130 18:07:07.845266 36 __init__.py:257] Found /usr/local/cuda/bin/nvcc(10.0.130) at /usr/local/cuda/bin/nvcc. [i 0130 18:07:07.861888 36 __init__.py:257] Found addr2line(2.30) at /usr/bin/addr2line. [i 0130 18:07:07.900882 36 compiler.py:889] pybind_include: -I/root/miniconda3/envs/myconda/include/python3.7m -I/root/miniconda3/envs/myconda/lib/python3.7/site-packages/pybind11/include [i 0130 18:07:07.926310 36 compiler.py:891] extension_suffix: .cpython-37m-x86_64-linux-gnu.so [i 0130 18:07:08.160195 36 __init__.py:169] Total mem: 62.54GB, using 16 procs for compiling. [i 0130 18:07:08.292372 36 jit_compiler.cc:21] Load cc_path: /usr/bin/g++ [i 0130 18:07:08.453513 36 init.cc:54] Found cuda archs: [75,] [i 0130 18:07:08.486432 36 compile_extern.py:384] mpicc not found, distribution disabled. [i 0130 18:07:08.549991 36 compile_extern.py:16] found /usr/local/cuda/include/cublas.h [i 0130 18:07:08.550087 36 compile_extern.py:16] found /usr/local/cuda/lib64/libcublas.so [i 0130 18:07:08.821434 36 compile_extern.py:16] found /usr/include/cudnn.h [i 0130 18:07:08.821595 36 compile_extern.py:16] found /usr/lib/x86_64-linux-gnu/libcudnn.so [i 0130 18:07:08.851032 36 compiler.py:654] handle pyjt_include/root/miniconda3/envs/myconda/lib/python3.7/site-packages/jittor/extern/cuda/cudnn/inc/cudnn_warper.h [i 0130 18:07:10.230110 36 compile_extern.py:16] found /usr/local/cuda/include/curand.h [i 0130 18:07:10.230265 36 compile_extern.py:16] found /usr/local/cuda/lib64/libcurand.so [i 0130 18:07:11.166735 36 cuda_flags.cc:26] CUDA enabled. terminate called after throwing an instance of 'std::runtime_error' what(): [f 0130 18:07:18.423952 36 jit_key.cc:41] Check failed: 0== mprotect((void*)buffer_end_page, page_size, 0x1|0x2|0x4) Something wrong... Could you please report this issue? — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.
